language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '10'
  - '11'
  - '8'
script:
  - npm run test:coverage
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
