language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '10'
  - '11'
  - '8'
script:
  - npm run test:coverage
after_success:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
