language: node_js
cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - 'node'
  - '10'
  - '11'
  - '8'

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: test
      script: npm test:prod
    - stage: coverage
      node_js: node
      script: npm run test:coverage && npm run report-coverage && rm -rf ./coverage

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
